name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Add Vue Package
        run: yarn add --peer vue

      - name: Run linter
        run: yarn lint

      - name: full-icu install
        run: npm install -g full-icu
      - name: set NODE_ICU_DATA path
        run: echo "NODE_ICU_DATA=`node-full-icu-path 2>/dev/null`" >> $GITHUB_ENV

      - name: Run tests
        run: yarn test:unit