name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14']

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Add Vue Package
        run: yarn add --peer vue

      - name: Run linter
        run: yarn lint

      - name: Run tests
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
        run: yarn test:unit