name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install

      - name: Add Vue Package
        run: yarn add --peer vue

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test:unit